# HOW2 

The following notebook will walk you through some basic python that will help you create triangles and graphs.
Make sure you **run all of the code blocks in the order they appear** in this notebook, as they can depend on each other.
I have tried to make the variable names as self explanatory as possible.

If a line starts with #, then it is a comment and will explain the code it surrounds.


## Imports
In the cell below, all that is happening is we are importing the packages we will be using in this tutorial

In [1]:
%matplotlib inline
import matplotlib
#from tabulate import tabulate
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

Where we have written e.g. ```import matplotlib.pyplot as plt``` all this means is we are importing it and renaming it under an alias we choose. This just makes our lives easier as when we want to call the function, we can just type ```plt``` instead of
the entire ```matplotlib.pyplot```

The ```%matplotlib inline``` allows us to view the graphs in this notebook

# Gross Premiums Received

In the section below, we will create triangles and graphs relating to the 'Gross Premiums Received' from the data in the data.csv file.

## Reading from a .csv File

In the cell below, we are reading the data in the .csv file into a DataFrame (using the ```pd.read_csv(FILENAME)``` function). A DataFrame is basically just a spreadsheet. You can name the DataFrame anything, in this example, we have chosen the variable name df.

By default, the ```.dropna()``` function returns a new DataFrame and removes any rows that contain NA values. The ```inplace = True``` is necessary to make the changes take place in **the same** DataFrame. Otherwise, you would have to reassign the variable, like: ```df = df.dropna()```. The option ```thresh=2``` defines a threshold. In this example, it deletes all rows that don't meet the threshold of having at least 2 non-NA values. 
If we didn't have this threshold, then all of the rows would be deleted, as the "unnamed" column contains an NaN value for each row. This is not the outcome we want.

We also don't want commas to be polluting our numbers so, to remove them, use ```df = df.replace(',','', regex = True)``` where the ```regex = True``` option will also replace commas inside substrings

The ```display(df)``` command will print a pretty table displaying the DataFrame.

In [2]:
df = pd.read_csv('data.csv')

df.dropna(inplace = True, thresh = 2)

# we could also remove any column that contains any number of Na values > 0 (we still need to do the above command, otherwise 
# every column would be removed!) uncomment the line below and run again to see what happens
#df.dropna(axis='columns', inplace=True)


df.replace(',','', regex = True, inplace=True)

# here we just change the pandas settings so we can see all the rows in the tables. You can change it if you would like. 
# see what happens when you change None to 4 (make sure to change it back afterwards for the rest of the tutorial)
pd.set_option("display.max_rows", None)

display(df)

# an alternative to display() is print(tabulate(df, headers = 'keys', tablefmt = 'pretty')), if you want to use it, uncomment
# it in the imports and install it on your machine

,Underwriting YoA,Processing Month,Gross Premiums Received,Gross Paid Claims,Gross Incurred Claims,Unnamed: 5,Process year,Process month,Development period,Premiums received - censored,Paid claims - censored,Incurred claims - censored
0,2013.0,201301.0,322983,0,0,NaN,2013.0,1.0,1.0,322983,0,0
1,2013.0,201302.0,5083516,112500,112500,NaN,2013.0,2.0,2.0,5083516,112500,112500
2,2013.0,201303.0,8812441,124813,183023,NaN,2013.0,3.0,3.0,8812441,124813,183023
3,2013.0,201304.0,12751060,153152,259558,NaN,2013.0,4.0,4.0,12751060,153152,259558
4,2013.0,201305.0,13346743,199386,509828,NaN,2013.0,5.0,5.0,13346743,199386,509828
5,2013.0,201306.0,15993573,371695,759277,NaN,2013.0,6.0,6.0,15993573,371695,759277
6,2013.0,201307.0,17618810,558040,1115204,NaN,2013.0,7.0,7.0,17618810,558040,1115204
7,2013.0,201308.0,20333060,967848,1832746,NaN,2013.0,8.0,8.0,20333060,967848,1832746
8,2013.0,201309.0,22002371,1277353,3068456,NaN,2013.0,9.0,9.0,22002371,1277353,3068456
9,2013.0,201310.0,23991350,2625446,7017086,NaN,2013.0,10.0,10.0,23991350,2625446,7017086
10,2013.0,201311.0,27751423,2883994,7436945,NaN,2013.0,11.0,11.0,27751423,2883994,7436945
11,2013.0,201312.0,29622534,4001752,8606379,NaN,2013.0,12.0,12.0,29622534,4001752,8606379
12,2013.0,201401.0,32191017,4283123,7487114,NaN,2014.0,1.0,13.0,32191017,4283123,7487114
13,2013.0,201402.0,34410535,5202063,8549561,NaN,2014.0,2.0,14.0,34410535,5202063,8549561
14,2013.0,201403.0,36561450,5837197,9344216,NaN,2014.0,3.0,15.0,36561450,5837197,9344216
15,2013.0,201404.0,38949612,6822248,10885200,NaN,2014.0,4.0,16.0,38949612,6822248,10885200
16,2013.0,201405.0,40884665,7484739,11853156,NaN,2014.0,5.0,17.0,40884665,7484739,11853156
17,2013.0,201406.0,42243166,8454242,12466380,NaN,2014.0,6.0,18.0,42243166,8454242,12466380
18,2013.0,201407.0,44294756,9003087,13561164,NaN,2014.0,7.0,19.0,44294756,9003087,13561164
19,2013.0,201408.0,45232258,9639517,14567469,NaN,2014.0,8.0,20.0,45232258,9639517,14567469
20,2013.0,201409.0,46398802,11131810,15432746,NaN,2014.0,9.0,21.0,46398802,11131810,15432746
21,2013.0,201410.0,48569422,12273968,16702028,NaN,2014.0,10.0,22.0,48569422,12273968,16702028
22,2013.0,201411.0,49333352,12584050,16606548,NaN,2014.0,11.0,23.0,49333352,12584050,16606548
23,2013.0,201412.0,50580042,13447315,17579265,NaN,2014.0,12.0,24.0,50580042,13447315,17579265
24,2013.0,201501.0,51109657,13829838,18053889,NaN,2015.0,1.0,25.0,51109657,13829838,18053889
25,2013.0,201502.0,51593285,14757924,18753905,NaN,2015.0,2.0,26.0,51593285,14757924,18753905
26,2013.0,201503.0,52761633,15409752,18869535,NaN,2015.0,3.0,27.0,52761633,15409752,18869535
27,2013.0,201504.0,52799879,16157438,19702605,NaN,2015.0,4.0,28.0,52799879,16157438,19702605
28,2013.0,201505.0,52784193,16983419,20003372,NaN,2015.0,5.0,29.0,52784193,16983419,20003372
29,2013.0,201506.0,53214864,17403454,20950432,NaN,2015.0,6.0,30.0,53214864,17403454,20950432
30,2013.0,201507.0,53501444,18078862,21597067,NaN,2015.0,7.0,31.0,53501444,18078862,21597067
31,2013.0,201508.0,53828788,18659279,21888273,NaN,2015.0,8.0,32.0,53828788,18659279,21888273
32,2013.0,201509.0,53817003,18528513,21669313,NaN,2015.0,9.0,33.0,53817003,18528513,21669313
33,2013.0,201510.0,53510496,18703240,22144025,NaN,2015.0,10.0,34.0,53510496,18703240,22144025
34,2013.0,201511.0,53466006,18882174,22471190,NaN,2015.0,11.0,35.0,53466006,18882174,22471190
35,2013.0,201512.0,53555346,19304416,22466988,NaN,2015.0,12.0,36.0,53555346,19304416,22466988
36,2013.0,201601.0,53567553,19481446,22535259,NaN,2016.0,1.0,37.0,53567553,19481446,22535259
37,2013.0,201602.0,53583020,19630267,22498453,NaN,2016.0,2.0,38.0,53583020,19630267,22498453
38,2013.0,201603.0,53608819,19810061,22611471,NaN,2016.0,3.0,39.0,53608819,19810061,22611471
39,2013.0,201604.0,53638795,19847457,22653670,NaN,2016.0,4.0,40.0,53638795,19847457,22653670
40,2013.0,201605.0,53630330,20015211,22746895,NaN,2016.0,5.0,41.0,53630330,20015211,22746895
41,2013.0,201606.0,53590474,20024855,22660945,NaN,2016.0,6.0,42.0,53590474,20024855,22660945
42,2013.0,201607.0,53593728,20355045,22674640,NaN,2016.0,7.0,43.0,53593728,20355045,22674640
43,2013.0,201608.0,53594516,20580888,22811380,NaN,2016.0,8.0,44.0,53594516,20580888,22811380
44,2013.0,201609.0,53595571,20666433,22764346,NaN,2016.0,9.0,45.0,53595571,20666433,22764346
45,2013.0,201610.0,53685460,20731381,22608762,NaN,2016.0,10.0,46.0,53685460,20731381,22608762
46,2013.0,201611.0,53604982,20823818,22562302,NaN,2016.0,11.0,47.0,53604982,20823818,22562302
47,2013.0,201612.0,53617097,20914999,22586879,NaN,2016.0,12.0,48.0,53617097,20914999,22586879
48,2013.0,201701.0,53584037,20922749,22343285,NaN,2017.0,1.0,49.0,53584037,20922749,22343285
49,2013.0,201702.0,53591945,21105841,22322502,NaN,2017.0,2.0,50.0,53591945,21105841,22322502
50,2013.0,201703.0,53596927,21122431,22330182,NaN,2017.0,3.0,51.0,53596927,21122431,22330182
51,2013.0,201704.0,53385656,21140731,22460708,NaN,2017.0,4.0,52.0,53385656,21140731,22460708
52,2013.0,201705.0,53515182,21288996,22562529,NaN,2017.0,5.0,53.0,53515182,21288996,22562529
53,2013.0,201706.0,53510028,21294942,22548881,NaN,2017.0,6.0,54.0,53510028,21294942,22548881
54,2013.0,201707.0,53520400,21506043,22665350,NaN,2017.0,7.0,55.0,53520400,21506043,22665350
55,2013.0,201708.0,53440068,21532392,22688224,NaN,2017.0,8.0,56.0,53440068,21532392,22688224
56,2013.0,201709.0,53439639,21526132,22680747,NaN,2017.0,9.0,57.0,53439639,21526132,22680747
57,2013.0,201712.0,53310131,21625972,22735758,NaN,2017.0,12.0,60.0,53310131,21625972,22735758
58,2014.0,201401.0,429263,0,0,NaN,2014.0,1.0,1.0,429263,0,0
59,2014.0,201402.0,3664094,0,433,NaN,2014.0,2.0,2.0,3664094,0,433
60,2014.0,201403.0,9070001,4663,14894,NaN,2014.0,3.0,3.0,9070001,4663,14894
61,2014.0,201404.0,9807319,41217,95591,NaN,2014.0,4.0,4.0,9807319,41217,95591
62,2014.0,201405.0,12577434,88016,200019,NaN,2014.0,5.0,5.0,12577434,88016,200019
63,2014.0,201406.0,14233825,358287,538744,NaN,2014.0,6.0,6.0,14233825,358287,538744
64,2014.0,201407.0,17366342,697917,919686,NaN,2014.0,7.0,7.0,17366342,697917,919686
65,2014.0,201408.0,19848826,773569,969792,NaN,2014.0,8.0,8.0,19848826,773569,969792
66,2014.0,201409.0,22048733,1088687,2723357,NaN,2014.0,9.0,9.0,22048733,1088687,2723357
67,2014.0,201410.0,24676600,1477936,3267343,NaN,2014.0,10.0,10.0,24676600,1477936,3267343
68,2014.0,201411.0,26503386,1599831,3407944,NaN,2014.0,11.0,11.0,26503386,1599831,3407944
69,2014.0,201412.0,28717798,1983457,5354752,NaN,2014.0,12.0,12.0,28717798,1983457,5354752
70,2014.0,201501.0,30843766,2387647,5460818,NaN,2015.0,1.0,13.0,30843766,2387647,5460818
71,2014.0,201502.0,33350535,3663583,7023747,NaN,2015.0,2.0,14.0,33350535,3663583,7023747
72,2014.0,201503.0,35592003,4597111,7316820,NaN,2015.0,3.0,15.0,35592003,4597111,7316820
73,2014.0,201504.0,37281168,5575191,8403875,NaN,2015.0,4.0,16.0,37281168,5575191,8403875
74,2014.0,201505.0,38928053,6355885,9189445,NaN,2015.0,5.0,17.0,38928053,6355885,9189445
75,2014.0,201506.0,40331163,7131460,9965836,NaN,2015.0,6.0,18.0,40331163,7131460,9965836
76,2014.0,201507.0,41579499,7977821,10753916,NaN,2015.0,7.0,19.0,41579499,7977821,10753916
77,2014.0,201508.0,43114241,9232363,11509100,NaN,2015.0,8.0,20.0,43114241,9232363,11509100
78,2014.0,201509.0,43985858,10430772,13154525,NaN,2015.0,9.0,21.0,43985858,10430772,13154525
79,2014.0,201510.0,45910175,12047907,15025730,NaN,2015.0,10.0,22.0,45910175,12047907,15025730
80,2014.0,201511.0,46653070,13760905,16112966,NaN,2015.0,11.0,23.0,46653070,13760905,16112966
81,2014.0,201512.0,47092556,14102998,16756258,NaN,2015.0,12.0,24.0,47092556,14102998,16756258
82,2014.0,201601.0,47217286,14671679,18042007,NaN,2016.0,1.0,25.0,47217286,14671679,18042007
83,2014.0,201602.0,47434267,15119760,18844068,NaN,2016.0,2.0,26.0,47434267,15119760,18844068
84,2014.0,201603.0,47659296,15528611,19084337,NaN,2016.0,3.0,27.0,47659296,15528611,19084337
85,2014.0,201604.0,47853735,15857003,19393678,NaN,2016.0,4.0,28.0,47853735,15857003,19393678
86,2014.0,201605.0,48293316,16595225,19972227,NaN,2016.0,5.0,29.0,48293316,16595225,19972227
87,2014.0,201606.0,48555336,16969213,20501983,NaN,2016.0,6.0,30.0,48555336,16969213,20501983
88,2014.0,201607.0,48677946,17139188,20266220,NaN,2016.0,7.0,31.0,48677946,17139188,20266220
89,2014.0,201608.0,48749608,17576821,25076450,NaN,2016.0,8.0,32.0,48749608,17576821,20523110
90,2014.0,201609.0,48877877,18129304,20783452,NaN,2016.0,9.0,33.0,48877877,18129304,20783452
91,2014.0,201610.0,49085985,18517718,20850143,NaN,2016.0,10.0,34.0,49085985,18517718,20850143
92,2014.0,201611.0,49197790,19142982,21314926,NaN,2016.0,11.0,35.0,49197790,19142982,21314926
93,2014.0,201612.0,49237542,19239497,21346720,NaN,2016.0,12.0,36.0,49237542,19239497,21346720
94,2014.0,201701.0,49234299,19350580,21350334,NaN,2017.0,1.0,37.0,49234299,19350580,21350334
95,2014.0,201702.0,49317842,19420672,21331634,NaN,2017.0,2.0,38.0,49317842,19420672,21331634
96,2014.0,201703.0,49325843,19606098,21428109,NaN,2017.0,3.0,39.0,49325843,19606098,21428109
97,2014.0,201704.0,49308824,19682519,21467750,NaN,2017.0,4.0,40.0,49308824,19682519,21467750
98,2014.0,201705.0,49339200,19704006,21382902,NaN,2017.0,5.0,41.0,49339200,19704006,21382902
99,2014.0,201706.0,49364121,19793319,21534283,NaN,2017.0,6.0,42.0,49364121,19793319,21534283
100,2014.0,201707.0,49367282,20060281,21581489,NaN,2017.0,7.0,43.0,49367282,20060281,21581489
101,2014.0,201708.0,49460784,20168708,21578314,NaN,2017.0,8.0,44.0,49460784,20168708,21578314
102,2014.0,201709.0,49467111,20200774,21607076,NaN,2017.0,9.0,45.0,49467111,20200774,21607076
103,2014.0,201712.0,49666802,20480758,21814915,NaN,2017.0,12.0,48.0,49666802,20480758,21814915
104,2015.0,201501.0,273587,1960,1960,NaN,2015.0,1.0,1.0,273587,1960,1960
105,2015.0,201502.0,6350506,16208,16208,NaN,2015.0,2.0,2.0,6350506,16208,16208
106,2015.0,201503.0,7990355,23528,23528,NaN,2015.0,3.0,3.0,7990355,23528,23528
107,2015.0,201504.0,9695011,56876,397588,NaN,2015.0,4.0,4.0,9695011,56876,397588
108,2015.0,201505.0,12016329,313208,417307,NaN,2015.0,5.0,5.0,12016329,313208,417307
109,2015.0,201506.0,13445556,407098,870758,NaN,2015.0,6.0,6.0,13445556,407098,870758
110,2015.0,201507.0,15882387,625755,1496336,NaN,2015.0,7.0,7.0,15882387,625755,1496336
111,2015.0,201508.0,18896115,760768,1899844,NaN,2015.0,8.0,8.0,18896115,760768,1899844
112,2015.0,201509.0,20951776,1398401,3858497,NaN,2015.0,9.0,9.0,20951776,1398401,3858497
113,2015.0,201510.0,23468360,2324353,4751811,NaN,2015.0,10.0,10.0,23468360,2324353,4751811
114,2015.0,201511.0,25983343,2770586,5336823,NaN,2015.0,11.0,11.0,25983343,2770586,5336823
115,2015.0,201512.0,28159003,3654319,6767157,NaN,2015.0,12.0,12.0,28159003,3654319,6767157
116,2015.0,201601.0,29965226,4195765,7170687,NaN,2016.0,1.0,13.0,29965226,4195765,7170687
117,2015.0,201602.0,31566795,4818285,7787018,NaN,2016.0,2.0,14.0,31566795,4818285,7787018
118,2015.0,201603.0,35087658,6725715,9297143,NaN,2016.0,3.0,15.0,35087658,6725715,9297143
119,2015.0,201604.0,36650943,7091523,9674942,NaN,2016.0,4.0,16.0,36650943,7091523,9674942
120,2015.0,201605.0,37327405,7667665,10184319,NaN,2016.0,5.0,17.0,37327405,7667665,10184319
121,2015.0,201606.0,38587679,7924457,10340450,NaN,2016.0,6.0,18.0,38587679,7924457,10340450
122,2015.0,201607.0,39528022,8594791,10756159,NaN,2016.0,7.0,19.0,39528022,8594791,10756159
123,2015.0,201608.0,40680224,8951172,11324247,NaN,2016.0,8.0,20.0,40680224,8951172,11324247
124,2015.0,201609.0,41569751,9210197,11586674,NaN,2016.0,9.0,21.0,41569751,9210197,11586674
125,2015.0,201610.0,42775155,9672317,11968393,NaN,2016.0,10.0,22.0,42775155,9672317,11968393
126,2015.0,201611.0,43164987,10314138,12782999,NaN,2016.0,11.0,23.0,43164987,10314138,12782999
127,2015.0,201612.0,43934895,10642198,12965060,NaN,2016.0,12.0,24.0,43934895,10642198,12965060
128,2015.0,201701.0,44346749,11107037,13485513,NaN,2017.0,1.0,25.0,44346749,11107037,13485513
129,2015.0,201702.0,44737051,11436003,13847230,NaN,2017.0,2.0,26.0,44737051,11436003,13847230
130,2015.0,201703.0,45067300,11688378,15275500,NaN,2017.0,3.0,27.0,45067300,11688378,15275500
131,2015.0,201704.0,45175491,11913475,15404439,NaN,2017.0,4.0,28.0,45175491,11913475,15404439
132,2015.0,201705.0,45317185,12413423,15902249,NaN,2017.0,5.0,29.0,45317185,12413423,15902249
133,2015.0,201706.0,45196798,12627112,16152478,NaN,2017.0,6.0,30.0,45196798,12627112,16152478
134,2015.0,201707.0,45456545,13196155,16722160,NaN,2017.0,7.0,31.0,45456545,13196155,16722160
135,2015.0,201708.0,45559042,13558727,17061216,NaN,2017.0,8.0,32.0,45559042,13558727,17061216
136,2015.0,201709.0,45614302,14144553,17634945,NaN,2017.0,9.0,33.0,45614302,14144553,17634945
137,2015.0,201712.0,46895051,15272204,18289966,NaN,2017.0,12.0,36.0,46895051,15272204,18289966
138,2016.0,201601.0,188806,21443,21443,NaN,2016.0,1.0,1.0,188806,21443,21443
139,2016.0,201602.0,4992894,29074,60130,NaN,2016.0,2.0,2.0,4992894,29074,60130
140,2016.0,201603.0,6578719,64746,115003,NaN,2016.0,3.0,3.0,6578719,64746,115003
141,2016.0,201604.0,8802753,95592,180221,NaN,2016.0,4.0,4.0,8802753,95592,180221
142,2016.0,201605.0,10685937,202753,311315,NaN,2016.0,5.0,5.0,10685937,202753,311315
143,2016.0,201606.0,12302122,293918,402268,NaN,2016.0,6.0,6.0,12302122,293918,402268
144,2016.0,201607.0,16527614,434659,688563,NaN,2016.0,7.0,7.0,16527614,434659,688563
145,2016.0,201608.0,18590920,932462,1372081,NaN,2016.0,8.0,8.0,18590920,932462,1372081
146,2016.0,201609.0,25479747,1486359,2445388,NaN,2016.0,9.0,9.0,20425496,1486359,2445388
147,2016.0,201610.0,22452988,1615246,2644478,NaN,2016.0,10.0,10.0,22452988,1615246,2644478
148,2016.0,201611.0,24820850,1959612,5703228,NaN,2016.0,11.0,11.0,24820850,1959612,5703228
149,2016.0,201612.0,27278453,2633750,6485711,NaN,2016.0,12.0,12.0,27278453,2633750,6485711
150,2016.0,201701.0,29563681,2802108,7261015,NaN,2017.0,1.0,13.0,29563681,2802108,7261015
151,2016.0,201702.0,31326632,3558969,8453855,NaN,2017.0,2.0,14.0,31326632,3558969,8453855
152,2016.0,201703.0,33573013,4686163,9519276,NaN,2017.0,3.0,15.0,33573013,4686163,9519276
153,2016.0,201704.0,34928123,5248684,11706128,NaN,2017.0,4.0,16.0,34928123,5248684,11706128
154,2016.0,201705.0,36845346,6119686,11953533,NaN,2017.0,5.0,17.0,36845346,6119686,11953533
155,2016.0,201706.0,37859542,6569760,12423675,NaN,2017.0,6.0,18.0,37859542,6569760,12423675
156,2016.0,201707.0,38691662,7939955,13394730,NaN,2017.0,7.0,19.0,38691662,7939955,13394730
157,2016.0,201708.0,40013895,8560071,13911421,NaN,2017.0,8.0,20.0,40013895,8560071,13911421
158,2016.0,201709.0,40906860,9955898,13949757,NaN,2017.0,9.0,21.0,40906860,9955898,13949757
159,2016.0,201712.0,44186990,11799686,17888478,NaN,2017.0,12.0,24.0,44186990,11799686,17888478
160,2017.0,201701.0,323277,11655,20425,NaN,2017.0,1.0,1.0,323277,11655,20425
161,2017.0,201702.0,4745863,28025,47587,NaN,2017.0,2.0,2.0,4745863,28025,47587
162,2017.0,201703.0,6467620,101185,173139,NaN,2017.0,3.0,3.0,6467620,101185,173139
163,2017.0,201704.0,7249042,136141,262230,NaN,2017.0,4.0,4.0,7249042,136141,262230
164,2017.0,201705.0,9699436,147393,334306,NaN,2017.0,5.0,5.0,9699436,147393,334306
165,2017.0,201706.0,12050793,384807,687749,NaN,2017.0,6.0,6.0,12050793,384807,687749
166,2017.0,201707.0,14246337,603797,1011248,NaN,2017.0,7.0,7.0,14246337,603797,1011248
167,2017.0,201708.0,18118460,855912,1397151,NaN,2017.0,8.0,8.0,18118460,855912,1397151
168,2017.0,201709.0,19887995,1269396,1772532,NaN,2017.0,9.0,9.0,19887995,1269396,1772532
169,2017.0,201712.0,26731635,2642138,3930626,NaN,2017.0,12.0,12.0,26731635,2642138,3930626

## Altering the DataFrame

2013.0 is a strange way to write a year, lets force it to be written as 2013. In other words, lets convert the type of the "Underwriting YoA" column from type float to be of type int. Lets also change the "Process Year" and "Development period" column just for fun.

I'm also going to convert the "Processing Month" column to type string for a later exercise. This is so it is subscriptable (This will be explained in more detail in the section). I'm going to convert it to int first though, to get rid of the decimal.

In [3]:
df[['Underwriting YoA','Development period','Processing Month','Process year']] = df[['Underwriting YoA','Development period','Processing Month','Process year']].astype('int')
df['Processing Month'] = df['Processing Month'].astype('str')
#You could also do this one-by-one but its better to do the above
#df['Underwriting YoA'] = df['Underwriting YoA'].astype('int')
#df['Process year'] = df['Process year'].astype('int')
#df['Processing Month'] = df['Processing Month'].astype('int')

display(df)

,Underwriting YoA,Processing Month,Gross Premiums Received,Gross Paid Claims,Gross Incurred Claims,Unnamed: 5,Process year,Process month,Development period,Premiums received - censored,Paid claims - censored,Incurred claims - censored
0,2013,201301,322983,0,0,NaN,2013,1.0,1,322983,0,0
1,2013,201302,5083516,112500,112500,NaN,2013,2.0,2,5083516,112500,112500
2,2013,201303,8812441,124813,183023,NaN,2013,3.0,3,8812441,124813,183023
3,2013,201304,12751060,153152,259558,NaN,2013,4.0,4,12751060,153152,259558
4,2013,201305,13346743,199386,509828,NaN,2013,5.0,5,13346743,199386,509828
5,2013,201306,15993573,371695,759277,NaN,2013,6.0,6,15993573,371695,759277
6,2013,201307,17618810,558040,1115204,NaN,2013,7.0,7,17618810,558040,1115204
7,2013,201308,20333060,967848,1832746,NaN,2013,8.0,8,20333060,967848,1832746
8,2013,201309,22002371,1277353,3068456,NaN,2013,9.0,9,22002371,1277353,3068456
9,2013,201310,23991350,2625446,7017086,NaN,2013,10.0,10,23991350,2625446,7017086
10,2013,201311,27751423,2883994,7436945,NaN,2013,11.0,11,27751423,2883994,7436945
11,2013,201312,29622534,4001752,8606379,NaN,2013,12.0,12,29622534,4001752,8606379
12,2013,201401,32191017,4283123,7487114,NaN,2014,1.0,13,32191017,4283123,7487114
13,2013,201402,34410535,5202063,8549561,NaN,2014,2.0,14,34410535,5202063,8549561
14,2013,201403,36561450,5837197,9344216,NaN,2014,3.0,15,36561450,5837197,9344216
15,2013,201404,38949612,6822248,10885200,NaN,2014,4.0,16,38949612,6822248,10885200
16,2013,201405,40884665,7484739,11853156,NaN,2014,5.0,17,40884665,7484739,11853156
17,2013,201406,42243166,8454242,12466380,NaN,2014,6.0,18,42243166,8454242,12466380
18,2013,201407,44294756,9003087,13561164,NaN,2014,7.0,19,44294756,9003087,13561164
19,2013,201408,45232258,9639517,14567469,NaN,2014,8.0,20,45232258,9639517,14567469
20,2013,201409,46398802,11131810,15432746,NaN,2014,9.0,21,46398802,11131810,15432746
21,2013,201410,48569422,12273968,16702028,NaN,2014,10.0,22,48569422,12273968,16702028
22,2013,201411,49333352,12584050,16606548,NaN,2014,11.0,23,49333352,12584050,16606548
23,2013,201412,50580042,13447315,17579265,NaN,2014,12.0,24,50580042,13447315,17579265
24,2013,201501,51109657,13829838,18053889,NaN,2015,1.0,25,51109657,13829838,18053889
25,2013,201502,51593285,14757924,18753905,NaN,2015,2.0,26,51593285,14757924,18753905
26,2013,201503,52761633,15409752,18869535,NaN,2015,3.0,27,52761633,15409752,18869535
27,2013,201504,52799879,16157438,19702605,NaN,2015,4.0,28,52799879,16157438,19702605
28,2013,201505,52784193,16983419,20003372,NaN,2015,5.0,29,52784193,16983419,20003372
29,2013,201506,53214864,17403454,20950432,NaN,2015,6.0,30,53214864,17403454,20950432
30,2013,201507,53501444,18078862,21597067,NaN,2015,7.0,31,53501444,18078862,21597067
31,2013,201508,53828788,18659279,21888273,NaN,2015,8.0,32,53828788,18659279,21888273
32,2013,201509,53817003,18528513,21669313,NaN,2015,9.0,33,53817003,18528513,21669313
33,2013,201510,53510496,18703240,22144025,NaN,2015,10.0,34,53510496,18703240,22144025
34,2013,201511,53466006,18882174,22471190,NaN,2015,11.0,35,53466006,18882174,22471190
35,2013,201512,53555346,19304416,22466988,NaN,2015,12.0,36,53555346,19304416,22466988
36,2013,201601,53567553,19481446,22535259,NaN,2016,1.0,37,53567553,19481446,22535259
37,2013,201602,53583020,19630267,22498453,NaN,2016,2.0,38,53583020,19630267,22498453
38,2013,201603,53608819,19810061,22611471,NaN,2016,3.0,39,53608819,19810061,22611471
39,2013,201604,53638795,19847457,22653670,NaN,2016,4.0,40,53638795,19847457,22653670
40,2013,201605,53630330,20015211,22746895,NaN,2016,5.0,41,53630330,20015211,22746895
41,2013,201606,53590474,20024855,22660945,NaN,2016,6.0,42,53590474,20024855,22660945
42,2013,201607,53593728,20355045,22674640,NaN,2016,7.0,43,53593728,20355045,22674640
43,2013,201608,53594516,20580888,22811380,NaN,2016,8.0,44,53594516,20580888,22811380
44,2013,201609,53595571,20666433,22764346,NaN,2016,9.0,45,53595571,20666433,22764346
45,2013,201610,53685460,20731381,22608762,NaN,2016,10.0,46,53685460,20731381,22608762
46,2013,201611,53604982,20823818,22562302,NaN,2016,11.0,47,53604982,20823818,22562302
47,2013,201612,53617097,20914999,22586879,NaN,2016,12.0,48,53617097,20914999,22586879
48,2013,201701,53584037,20922749,22343285,NaN,2017,1.0,49,53584037,20922749,22343285
49,2013,201702,53591945,21105841,22322502,NaN,2017,2.0,50,53591945,21105841,22322502
50,2013,201703,53596927,21122431,22330182,NaN,2017,3.0,51,53596927,21122431,22330182
51,2013,201704,53385656,21140731,22460708,NaN,2017,4.0,52,53385656,21140731,22460708
52,2013,201705,53515182,21288996,22562529,NaN,2017,5.0,53,53515182,21288996,22562529
53,2013,201706,53510028,21294942,22548881,NaN,2017,6.0,54,53510028,21294942,22548881
54,2013,201707,53520400,21506043,22665350,NaN,2017,7.0,55,53520400,21506043,22665350
55,2013,201708,53440068,21532392,22688224,NaN,2017,8.0,56,53440068,21532392,22688224
56,2013,201709,53439639,21526132,22680747,NaN,2017,9.0,57,53439639,21526132,22680747
57,2013,201712,53310131,21625972,22735758,NaN,2017,12.0,60,53310131,21625972,22735758
58,2014,201401,429263,0,0,NaN,2014,1.0,1,429263,0,0
59,2014,201402,3664094,0,433,NaN,2014,2.0,2,3664094,0,433
60,2014,201403,9070001,4663,14894,NaN,2014,3.0,3,9070001,4663,14894
61,2014,201404,9807319,41217,95591,NaN,2014,4.0,4,9807319,41217,95591
62,2014,201405,12577434,88016,200019,NaN,2014,5.0,5,12577434,88016,200019
63,2014,201406,14233825,358287,538744,NaN,2014,6.0,6,14233825,358287,538744
64,2014,201407,17366342,697917,919686,NaN,2014,7.0,7,17366342,697917,919686
65,2014,201408,19848826,773569,969792,NaN,2014,8.0,8,19848826,773569,969792
66,2014,201409,22048733,1088687,2723357,NaN,2014,9.0,9,22048733,1088687,2723357
67,2014,201410,24676600,1477936,3267343,NaN,2014,10.0,10,24676600,1477936,3267343
68,2014,201411,26503386,1599831,3407944,NaN,2014,11.0,11,26503386,1599831,3407944
69,2014,201412,28717798,1983457,5354752,NaN,2014,12.0,12,28717798,1983457,5354752
70,2014,201501,30843766,2387647,5460818,NaN,2015,1.0,13,30843766,2387647,5460818
71,2014,201502,33350535,3663583,7023747,NaN,2015,2.0,14,33350535,3663583,7023747
72,2014,201503,35592003,4597111,7316820,NaN,2015,3.0,15,35592003,4597111,7316820
73,2014,201504,37281168,5575191,8403875,NaN,2015,4.0,16,37281168,5575191,8403875
74,2014,201505,38928053,6355885,9189445,NaN,2015,5.0,17,38928053,6355885,9189445
75,2014,201506,40331163,7131460,9965836,NaN,2015,6.0,18,40331163,7131460,9965836
76,2014,201507,41579499,7977821,10753916,NaN,2015,7.0,19,41579499,7977821,10753916
77,2014,201508,43114241,9232363,11509100,NaN,2015,8.0,20,43114241,9232363,11509100
78,2014,201509,43985858,10430772,13154525,NaN,2015,9.0,21,43985858,10430772,13154525
79,2014,201510,45910175,12047907,15025730,NaN,2015,10.0,22,45910175,12047907,15025730
80,2014,201511,46653070,13760905,16112966,NaN,2015,11.0,23,46653070,13760905,16112966
81,2014,201512,47092556,14102998,16756258,NaN,2015,12.0,24,47092556,14102998,16756258
82,2014,201601,47217286,14671679,18042007,NaN,2016,1.0,25,47217286,14671679,18042007
83,2014,201602,47434267,15119760,18844068,NaN,2016,2.0,26,47434267,15119760,18844068
84,2014,201603,47659296,15528611,19084337,NaN,2016,3.0,27,47659296,15528611,19084337
85,2014,201604,47853735,15857003,19393678,NaN,2016,4.0,28,47853735,15857003,19393678
86,2014,201605,48293316,16595225,19972227,NaN,2016,5.0,29,48293316,16595225,19972227
87,2014,201606,48555336,16969213,20501983,NaN,2016,6.0,30,48555336,16969213,20501983
88,2014,201607,48677946,17139188,20266220,NaN,2016,7.0,31,48677946,17139188,20266220
89,2014,201608,48749608,17576821,25076450,NaN,2016,8.0,32,48749608,17576821,20523110
90,2014,201609,48877877,18129304,20783452,NaN,2016,9.0,33,48877877,18129304,20783452
91,2014,201610,49085985,18517718,20850143,NaN,2016,10.0,34,49085985,18517718,20850143
92,2014,201611,49197790,19142982,21314926,NaN,2016,11.0,35,49197790,19142982,21314926
93,2014,201612,49237542,19239497,21346720,NaN,2016,12.0,36,49237542,19239497,21346720
94,2014,201701,49234299,19350580,21350334,NaN,2017,1.0,37,49234299,19350580,21350334
95,2014,201702,49317842,19420672,21331634,NaN,2017,2.0,38,49317842,19420672,21331634
96,2014,201703,49325843,19606098,21428109,NaN,2017,3.0,39,49325843,19606098,21428109
97,2014,201704,49308824,19682519,21467750,NaN,2017,4.0,40,49308824,19682519,21467750
98,2014,201705,49339200,19704006,21382902,NaN,2017,5.0,41,49339200,19704006,21382902
99,2014,201706,49364121,19793319,21534283,NaN,2017,6.0,42,49364121,19793319,21534283
100,2014,201707,49367282,20060281,21581489,NaN,2017,7.0,43,49367282,20060281,21581489
101,2014,201708,49460784,20168708,21578314,NaN,2017,8.0,44,49460784,20168708,21578314
102,2014,201709,49467111,20200774,21607076,NaN,2017,9.0,45,49467111,20200774,21607076
103,2014,201712,49666802,20480758,21814915,NaN,2017,12.0,48,49666802,20480758,21814915
104,2015,201501,273587,1960,1960,NaN,2015,1.0,1,273587,1960,1960
105,2015,201502,6350506,16208,16208,NaN,2015,2.0,2,6350506,16208,16208
106,2015,201503,7990355,23528,23528,NaN,2015,3.0,3,7990355,23528,23528
107,2015,201504,9695011,56876,397588,NaN,2015,4.0,4,9695011,56876,397588
108,2015,201505,12016329,313208,417307,NaN,2015,5.0,5,12016329,313208,417307
109,2015,201506,13445556,407098,870758,NaN,2015,6.0,6,13445556,407098,870758
110,2015,201507,15882387,625755,1496336,NaN,2015,7.0,7,15882387,625755,1496336
111,2015,201508,18896115,760768,1899844,NaN,2015,8.0,8,18896115,760768,1899844
112,2015,201509,20951776,1398401,3858497,NaN,2015,9.0,9,20951776,1398401,3858497
113,2015,201510,23468360,2324353,4751811,NaN,2015,10.0,10,23468360,2324353,4751811
114,2015,201511,25983343,2770586,5336823,NaN,2015,11.0,11,25983343,2770586,5336823
115,2015,201512,28159003,3654319,6767157,NaN,2015,12.0,12,28159003,3654319,6767157
116,2015,201601,29965226,4195765,7170687,NaN,2016,1.0,13,29965226,4195765,7170687
117,2015,201602,31566795,4818285,7787018,NaN,2016,2.0,14,31566795,4818285,7787018
118,2015,201603,35087658,6725715,9297143,NaN,2016,3.0,15,35087658,6725715,9297143
119,2015,201604,36650943,7091523,9674942,NaN,2016,4.0,16,36650943,7091523,9674942
120,2015,201605,37327405,7667665,10184319,NaN,2016,5.0,17,37327405,7667665,10184319
121,2015,201606,38587679,7924457,10340450,NaN,2016,6.0,18,38587679,7924457,10340450
122,2015,201607,39528022,8594791,10756159,NaN,2016,7.0,19,39528022,8594791,10756159
123,2015,201608,40680224,8951172,11324247,NaN,2016,8.0,20,40680224,8951172,11324247
124,2015,201609,41569751,9210197,11586674,NaN,2016,9.0,21,41569751,9210197,11586674
125,2015,201610,42775155,9672317,11968393,NaN,2016,10.0,22,42775155,9672317,11968393
126,2015,201611,43164987,10314138,12782999,NaN,2016,11.0,23,43164987,10314138,12782999
127,2015,201612,43934895,10642198,12965060,NaN,2016,12.0,24,43934895,10642198,12965060
128,2015,201701,44346749,11107037,13485513,NaN,2017,1.0,25,44346749,11107037,13485513
129,2015,201702,44737051,11436003,13847230,NaN,2017,2.0,26,44737051,11436003,13847230
130,2015,201703,45067300,11688378,15275500,NaN,2017,3.0,27,45067300,11688378,15275500
131,2015,201704,45175491,11913475,15404439,NaN,2017,4.0,28,45175491,11913475,15404439
132,2015,201705,45317185,12413423,15902249,NaN,2017,5.0,29,45317185,12413423,15902249
133,2015,201706,45196798,12627112,16152478,NaN,2017,6.0,30,45196798,12627112,16152478
134,2015,201707,45456545,13196155,16722160,NaN,2017,7.0,31,45456545,13196155,16722160
135,2015,201708,45559042,13558727,17061216,NaN,2017,8.0,32,45559042,13558727,17061216
136,2015,201709,45614302,14144553,17634945,NaN,2017,9.0,33,45614302,14144553,17634945
137,2015,201712,46895051,15272204,18289966,NaN,2017,12.0,36,46895051,15272204,18289966
138,2016,201601,188806,21443,21443,NaN,2016,1.0,1,188806,21443,21443
139,2016,201602,4992894,29074,60130,NaN,2016,2.0,2,4992894,29074,60130
140,2016,201603,6578719,64746,115003,NaN,2016,3.0,3,6578719,64746,115003
141,2016,201604,8802753,95592,180221,NaN,2016,4.0,4,8802753,95592,180221
142,2016,201605,10685937,202753,311315,NaN,2016,5.0,5,10685937,202753,311315
143,2016,201606,12302122,293918,402268,NaN,2016,6.0,6,12302122,293918,402268
144,2016,201607,16527614,434659,688563,NaN,2016,7.0,7,16527614,434659,688563
145,2016,201608,18590920,932462,1372081,NaN,2016,8.0,8,18590920,932462,1372081
146,2016,201609,25479747,1486359,2445388,NaN,2016,9.0,9,20425496,1486359,2445388
147,2016,201610,22452988,1615246,2644478,NaN,2016,10.0,10,22452988,1615246,2644478
148,2016,201611,24820850,1959612,5703228,NaN,2016,11.0,11,24820850,1959612,5703228
149,2016,201612,27278453,2633750,6485711,NaN,2016,12.0,12,27278453,2633750,6485711
150,2016,201701,29563681,2802108,7261015,NaN,2017,1.0,13,29563681,2802108,7261015
151,2016,201702,31326632,3558969,8453855,NaN,2017,2.0,14,31326632,3558969,8453855
152,2016,201703,33573013,4686163,9519276,NaN,2017,3.0,15,33573013,4686163,9519276
153,2016,201704,34928123,5248684,11706128,NaN,2017,4.0,16,34928123,5248684,11706128
154,2016,201705,36845346,6119686,11953533,NaN,2017,5.0,17,36845346,6119686,11953533
155,2016,201706,37859542,6569760,12423675,NaN,2017,6.0,18,37859542,6569760,12423675
156,2016,201707,38691662,7939955,13394730,NaN,2017,7.0,19,38691662,7939955,13394730
157,2016,201708,40013895,8560071,13911421,NaN,2017,8.0,20,40013895,8560071,13911421
158,2016,201709,40906860,9955898,13949757,NaN,2017,9.0,21,40906860,9955898,13949757
159,2016,201712,44186990,11799686,17888478,NaN,2017,12.0,24,44186990,11799686,17888478
160,2017,201701,323277,11655,20425,NaN,2017,1.0,1,323277,11655,20425
161,2017,201702,4745863,28025,47587,NaN,2017,2.0,2,4745863,28025,47587
162,2017,201703,6467620,101185,173139,NaN,2017,3.0,3,6467620,101185,173139
163,2017,201704,7249042,136141,262230,NaN,2017,4.0,4,7249042,136141,262230
164,2017,201705,9699436,147393,334306,NaN,2017,5.0,5,9699436,147393,334306
165,2017,201706,12050793,384807,687749,NaN,2017,6.0,6,12050793,384807,687749
166,2017,201707,14246337,603797,1011248,NaN,2017,7.0,7,14246337,603797,1011248
167,2017,201708,18118460,855912,1397151,NaN,2017,8.0,8,18118460,855912,1397151
168,2017,201709,19887995,1269396,1772532,NaN,2017,9.0,9,19887995,1269396,1772532
169,2017,201712,26731635,2642138,3930626,NaN,2017,12.0,12,26731635,2642138,3930626

## Displaying a triangle

### Creating a new dataFrame 

This DataFrame will contain only the columns we need. We will need to do some adjusting to the code before we can plot everything, as it doesn't look exactly as we need it to.
For example, as you can see in the 'Underwriting YoA' column, the years are repeated. This is not ideal as our aim is to display the data similarly to this (cropped image):
![](example_triangle.png)

### Extracting the data we need

We only need the two columns 'Underwriting YoA' and 'Gross Premiums Received' to create the gross premiums triangle. So we should create another DataFrame that only contains this.
We also need the amount of months after the underwriting year, but we can infer this from the 'Underwriting YoA' paired with the positioning in the DataFrame.  
  
The code might look like a lot, but its just because its heavily commented, there is actually only 14 lines of code (ignoring the 4 print statements).

In [ ]:
# here we are creating a new, smaller DataFrame, and storing only the 2 columns we need in it 
year_and_gross_premiums_received = df[['Underwriting YoA','Gross Premiums Received']].copy()

# uncomment the line below if you would like to see what the new DataFrame looks like
#display(year_and_gross_premiums_received)

#a variable that holds a list of the lengths of time in months after the underwriting years
length_of_time = []
# a variable that holds a list of the underwriting years
years = []

# a variable that holds the current year selected, so we are able to tell when it changes,
# here, to start with, we are setting it to be equal to the first value in the Underwriting YoA column
current_year_selected = year_and_gross_premiums_received['Underwriting YoA'][0]
years.append(current_year_selected)

# a variable to keep track of the number of iterations there has been for each year (which tells us the number of months
# after the underwriting year we have data for)
i = 0

# The below for loop iterates over each value in the Underwriting YoA column and, if the year has changed, it adds it 
# to the end of the list of years (using append(year)), it also adds i (explained above) to a list of the lengths of time
for year in year_and_gross_premiums_received['Underwriting YoA']:
    # != means "not equal"
    if current_year_selected != year:
        # we set "i" back to 0 as the year has changed, so we want to start measuring from 0 again
        length_of_time.append(i)
        i=0
        current_year_selected = year
        years.append(year)
    #we increment i outside of the above for loop as we want to keep track of the length of time when the year doesn't change
    i += 1
# we append once more, as the values of the last year won't have been caught by the if condition 
# this is because the year won't have changed again before the table ends 
length_of_time.append(i)
        
print("this is the list of lengths of time in months: " + str(length_of_time))
print("this is the list of years: " + str(years) + "\n")
print("if the list of lengths of time is confusing, look at the table we printed in the exercise before, and note that there ")
print("are 58 (inc 0) datapoints corresponding to 2013, and 46 to 2014 and so on.\n ")

### More data!

Now, we need to associate the data from the 'Gross Premiums Received' column to the appropriate year and length of time in months.
We will do this by creating a dictionary of values where each key is the year, and each year's value is a list of the Gross Premium Received values corresponding to the amount of time in months that has elapsed since the underwriting year.

If you want to know more about dictionaries, look in the [python documentation here](https://docs.python.org/3/tutorial/datastructures.html#dictionaries)

In [ ]:
# instantiate a new dictionary
years_gross_premiums_data = {}

# we will use j to keep track of the current index of the datapoint we need
j=0

# we are going to go through the years and create a dictionary where the key is the year and the value is a list of 
# all the values corresponding to that year in the 'Gross Premiums Received' column
for i, year in enumerate(years):
    ref_time_unit_list = []
    #for each year that has elapsed after the underwriting year (for each underwriting year)
    for time_unit in range(length_of_time[i]):
        ref_time_unit_list.append(int(year_and_gross_premiums_received['Gross Premiums Received'][j]))
        years_gross_premiums_data[year] = ref_time_unit_list
        #increment j
        j+=1

print("This is the dictionary we just created: \n" + str(years_gross_premiums_data))

### Convert the dictionary into a DataFrame

In order to convert the dictionary we just made into another DataFrame, all the arrays in the values need to be of the same length, so we will make them all as long as the longest array by padding the remaining length with NaN values.
We will also add a totals row and a totals column (similarly to the example) and then add these to the DataFrame.

In [ ]:
#first, find the size of the biggest array
largest_array_size = max(length_of_time)

# now we can pad with 0s (just because the arrays need to be the same size for us to convert it into a DataFrame) 
for year in years_gross_premiums_data:
    for i in range(largest_array_size - len(years_gross_premiums_data[year])):
        years_gross_premiums_data[year].append(np.nan)
    
# now we are able to convert the dictionary we built into a DataFrame, and display this
df_years_gross_prem = pd.DataFrame(years_gross_premiums_data) 

# I am keeping a copy of the data without the totals row and column for use in the graphs later
df1 = df_years_gross_prem.copy()

#we will add a 'Total' row
df_years_gross_prem.loc['Total1'] = df_years_gross_prem.sum(numeric_only = True, axis = 0)
#This will add a 'Total' column
df_years_gross_prem.loc[:,'Total2'] = df_years_gross_prem.sum(numeric_only = True, axis = 1)

display(df_years_gross_prem)

### Transposing the DataFrame

We want to display our table with the rows and columns the other way around. We can do this with one function: ```transpose()```.

In [ ]:
#we will transpose it to get the orientation we want
df_years_gross_prem = df_years_gross_prem.transpose()

display(df_years_gross_prem)

### Displaying all columns

The graph above might have limited your table and omitted some rows! If it did, and you want to view the whole table, you can easily do this by setting the ```pd.set_option("display.max_columns", NUMBER)``` to something high, or the value None.

In [ ]:
pd.set_option("display.max_columns", None)
display(df_years_gross_prem)

## Displaying Graphs

In this next section we will display the Gross Premiums as a graph similar to this (we won't let it drop down):
![](Gross_premiums_graph_example.png)

### Plot the graph

We just need to use two functions for this, since we already adjusted our DataFrame in the other exercise! If you use ```df.plot.line()``` it plots all the numerical columns as separate lines.

In [ ]:
# N.B. df1 is the DataFrame we used before, just without the totals row and column and without being transposed
ax = df1.plot.line()
# "print" the graph
plt.show()

### Add the axis labels, etc

You may want to clean up the graph a bit by adding axes labels and a title.  
It might also be worth changing the settings so all your graphs appear bigger.  
You may also want to be able to save the graph as an image.  
If you are struggling with this, or want to know more, the [matplotlib documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.html) will help, and so will the [pandas.DataFrame.plot documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html).

In [ ]:
# makes our graph a little bit bigger
plt.rcParams['figure.dpi'] = 100
plt.rcParams['figure.figsize']=(10, 7)

# plot our DataFrame  
ax = df1.plot.line()

# create axes labels and title the graph
ax.set(xlabel='Time elapsed (months)', ylabel='Gross Premiums Received', title='Gross Premiums Received')

#If you want to display the y axis as $50M, you can create a function to do this (we can then call this later on)
def yaxisFormatting(x, y):
    return str('${:.0f}'.format(x/1000000) +'M')
                                      
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))

# If you want to display the y axis in the form $50,000,000, comment out the line above and uncomment the line below
#plt.gca().yaxis.set_major_formatter(plt.matplotlib.ticker.StrMethodFormatter('${x:,.0f}'))

# this will save the graph as an image, search in the directory you are in and open it
plt.savefig('gross_prem_graph.png')

# if you wanted to plot multiple graphs in the same figure, this is also possible 
# if you wanted to display the graphs as next to each other, change fig, axes = plt.subplots(1,2)
fig1, axes = plt.subplots(2)

#setting a figure title
fig1.suptitle('DISPLAYING MULTIPLE GRAPHS:')

# im just plotting the same graph twice. If you want to plot different ones, change a df1 to the name of a different DataFrame
df1.plot(ax= axes[0]) 
df1.plot(ax= axes[1]) 

# "print" the graphs
plt.show()

# Gross Incurred Claims

Now, lets progress onto the Gross Incurred Claims column.    
Remember, the data.csv file is still stored in the DataFrame called df, so we don't need to read the file again.  

You may have noticed that a lot of the code we did in the previous sections is quite general, and we could repurpose a lot of it for this column.
Lets make some functions - these allow us to re-use code.

## Functions

We still will need to create the new DataFrame using the columns we need manually. The function we will make will do pretty much the exact same thing as what we did in the "Extracting the data we need" and the "More data!" sections for Gross Premiums Received. In addition to this though, it will also convert the dictionary we create into a DataFrame.  
Most of the code below should look familiar, I have just taken out the comments and introduced a few new variables to make it more general.

Any new piece of code will have a comment.

In [ ]:
# here we are creating a new, smaller DataFrame, and storing only the 2 columns we need in it 
year_and_gross_incurred = df[['Underwriting YoA','Gross Incurred Claims']].copy()

# uncomment the line below if you would like to see what the new DataFrame looks like
#display(year_and_gross_incurred)

# in this function, we create a new DataFrame, using a different DataFrame as a parameter (later, we will call the function
# with the year_and_gross_Incurred DataFrame we just made
def createTriangleDataFrame(originalDF):
    #The outlined block below is almost exactly the same as in the "Extracting the data we need" section
    #__________________________________________________________________________________________________________________________
    length_of_time = []
    years = []
    current_year_selected = originalDF['Underwriting YoA'][0]
    years.append(current_year_selected)
    i = 0
    for year in originalDF['Underwriting YoA']:
        if current_year_selected != year:
            length_of_time.append(i)
            i=0
            current_year_selected = year
            years.append(year)
        i += 1
    length_of_time.append(i)
    #__________________________________________________________________________________________________________________________
    #The outlined block of data below is almost the exact same as the "More data!" section 
    #__________________________________________________________________________________________________________________________
    originalDFDictionary = {}
    j=0
    for year in years:
        i = years.index(year)
        ref_time_unit_list = []
        #the line below is new, basically we are just extracting the name of the desired column from the DataFrame
        target_column = originalDF.columns.values.tolist()[1]
        for time_unit in range(length_of_time[i]):
            ref_time_unit_list.append(int(originalDF[target_column][j]))
            originalDFDictionary[year] = ref_time_unit_list
            j+=1
    #__________________________________________________________________________________________________________________________
    #The outlined block of data below is almost the exact same as the first half of the "Convert the dictionary into a DataFrame"
    #__________________________________________________________________________________________________________________________
    temp_array = length_of_time.copy()
    temp_array.sort()
    largest_array_size = temp_array[len(temp_array)-1]
    for year in originalDFDictionary:
        for i in range(largest_array_size - len(originalDFDictionary[year])):
            originalDFDictionary[year].append(np.nan)
    # a function returns exactly one thing. We are returning our updated DataFrame        
    return pd.DataFrame(originalDFDictionary)
    #__________________________________________________________________________________________________________________________


# we assign the return value from our createTriangleDataFrame function and assign it to a new variable
df_year_and_gross_incurred = createTriangleDataFrame(year_and_gross_incurred)
display(df_year_and_gross_incurred)

# if you want to prove to yourself it does the same as the other one (remember this is before we transpose it!) comment out the 
# 2 lines above and uncomment the 2 lines below to see it work for Gross Premiums Received

#df_year_and_gross_premiums_received = createTriangleDataFrame(year_and_gross_premiums_received)
#display(df_year_and_gross_premiums_received)

## Transposing and totals function

Lets create another function that will take a DataFrame as input, insert the totals columns and transpose it.

In [ ]:
def totalsAndTranspose(originalDF): 
    #create a new DataFrame, so we can still use the original without totals for graphing
    copyDF = originalDF.copy()
    #we will add a 'Total' row
    copyDF.loc['Total1'] = copyDF.sum(numeric_only = True, axis = 0)
    #This will add a 'Total' column
    copyDF.loc[:,'Total2'] = copyDF.sum(numeric_only = True, axis = 1)
    #we will transpose it to get the orientation we want
    return copyDF.transpose()

#call the function we just created with df_year_and_gross_incurred
display(totalsAndTranspose(df_year_and_gross_incurred))

##  Displaying Graphs Again

The below is very similar to the section inside Gross Premiums Received.  
See if you can save the figure as an image called "gross_incurred_graph.png"

In [ ]:
# plot our DataFrame  
ax = df_year_and_gross_incurred.plot.line()

# create axes labels and title the graph
ax.set(xlabel='Time elapsed (months)', ylabel='Gross Incurred Claims', title='Gross Incurred Claims')

#change the format of the labels on the y axis
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))

#save the figure as an image below this comment (before plt.show())

plt.show()

# Gross Paid Claims

Now, lets progress onto displaying the triangle and graph for the Gross Paid claims column.

This should be easy with our functions! :)

In [ ]:
# get the columns we need
year_and_gross_paid = df[['Underwriting YoA','Gross Paid Claims']].copy()

# use the functions we made before
df_year_and_gross_paid = createTriangleDataFrame(year_and_gross_paid)
display(totalsAndTranspose(df_year_and_gross_paid))

#create a graph
ax = df_year_and_gross_paid.plot.line()
ax.set(xlabel='Time elapsed (months)', ylabel='Gross Paid Claims', title='Gross Paid Claims')
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))
plt.show()

# Creating Pivot Tables

Lets move on and create pivot tables for each of the columns we worked with before. We will be using a built in pandas function that will be much quicker than what we did before. 

# Gross Premiums Received

We want to create a pivot table with the Underwriting YoA against the Development period. 

## Finding the development periods
The development period values are held in another column in our DataFrame, but as an extra challenge, lets instead infer it from the processing months. The development period will be the current Processing Month minus the last Processing Month. It also needs to restart from 0 for every new underwriting year.

At the very beginning of this HOW2, we converted the "Processing Month" from a float to a string. We did this so we could do something called [string slicing](https://www.digitalocean.com/community/tutorials/how-to-index-and-slice-strings-in-python-3). It means you can extract a substring from a string. This will allow us to very easily extract the month from the value, as it is formatted like this: "201301".

In [ ]:
# creating a DataFrame with the 3 columns we will need
gross_prems_piv= df[['Underwriting YoA','Processing Month','Gross Premiums Received']].copy()

#variables to hold a list of the years, and the months

prev_year = df['Underwriting YoA'][0]
#print(year +" from " + df['Processing Month'][0])
months = []
base = 0
prev_month = 0

for i, process_month in enumerate(df['Processing Month']):
    # using string slicing to extract the month from the process_month (remember it's of the format YYYYMM)
    month = int(process_month[4:6])
    year = df['Underwriting YoA'][i]
    
    # restart the base for every new underwriting year
    if year != prev_year:
        prev_year = year
        base = i  
        
    #if its the first development period of the year, start the base at 0 again
    if (i - base) == 0:
        months.append(month)
        
    #if the previous month was december and now its jan, we dont want to add (1-12), we want to add (13-1)
    elif prev_month > month:
        difference = (month + 12) - prev_month
        months.append(months[i-1] + difference)
        
   # otherwise add the difference between months
    else:
        difference = month - prev_month
        months.append(months[i-1] + difference)
    prev_month = month
    
    
# add the resulting list as a column in our DataFrame 
gross_prems_piv['Development period'] = months

# lets check if our column is correct using .equals with the Development period column in the original DataFrame
print("They are the same: " + str(gross_prems_piv['Development period'].equals(df['Development period'])))

## We can be more efficient...

Lets find the development period using vector calculations instead. The formula we want to use is: (Processing year - Underwriting YoA) *12 + Processing month

We can start by splitting Processing Month into two columns: Processing Year and Processing Month.

In [4]:
# creating a DataFrame with the 3 columns we will need
vec_gross_prems_piv= df[['Underwriting YoA','Processing Month','Gross Premiums Received']].copy()

# making'Processing Month' into 2 columns: 'Processing Month' and 'Processing Year'
# using a built in function str to string slice every value in column aand then converting it to integers again
# so we can use the values in our calculations
vec_gross_prems_piv['Processing Year'] = vec_gross_prems_piv['Processing Month'].str[:4].astype('int')
vec_gross_prems_piv['Processing Month'] = vec_gross_prems_piv['Processing Month'].str[4:6].astype('int')

#using our formula to create a new column containing the development periods
vec_gross_prems_piv['Development period'] = (vec_gross_prems_piv['Processing Year']-vec_gross_prems_piv['Underwriting YoA'])*12 + vec_gross_prems_piv['Processing Month']

# lets check if our new column is the same as in the original DataFrame
print("They are the same: " + str(vec_gross_prems_piv['Development period'].equals(df['Development period'])))

They are the same: True

## Creating the pivot table

Theres a built in function in pandas for this!

In [ ]:
table_gross_prems = pd.pivot_table(vec_gross_prems_piv, values='Gross Premiums Received', index=['Underwriting YoA'],
                    columns=['Development period'])

display(table_gross_prems)

# Gross Incurred Claims

## Creating the pivot table

Lets create a pivot table for Gross Incurred claims! this should be easy, given that we have already worked out the Development period, and can append this to a new DataFrame

In [ ]:
# create our dataframe 
gross_inc_piv= df[['Underwriting YoA','Processing Month','Gross Incurred Claims']].copy()

# making'Processing Month' into 2 columns: 'Processing Month' and 'Processing Year' 
gross_inc_piv['Processing Year'] = gross_inc_piv['Processing Month'].str[:4].astype('int')
gross_inc_piv['Processing Month'] = gross_inc_piv['Processing Month'].str[4:6].astype('int')

#using our formula to create a new column containing the development periods
gross_inc_piv['Development period'] = (gross_inc_piv['Processing Year']-gross_inc_piv['Underwriting YoA'])*12 + gross_inc_piv['Processing Month']

# create our pivot table
table_gross_inc = pd.pivot_table(gross_inc_piv, values='Gross Incurred Claims', index=['Underwriting YoA'],
                  columns=['Development period'])

display(table_gross_inc)

# Gross Paid Claims

## Creating the pivot table

For the last example, I wont use the development period we calculated, and will instead use the original values from the dataframe (even though they are the exact same).

In [ ]:
# create our dataframe 
gross_paid_piv= df[['Underwriting YoA','Processing Month','Gross Paid Claims', 'Development period']].copy()
# create our pivot table
table_gross_paid = pd.pivot_table(gross_paid_piv, values='Gross Paid Claims', index=['Underwriting YoA'],
                   columns=['Development period'])

display(table_gross_paid)

# Creating graphs from the pivot tables

## Gross Premiums Received
We'll once again start with Gross Premiums Received.

We can't just straight away plot the pivot table using .plot.line() because it will plot the wrong indexes, we want to transpose it first. If you want further explanation, read the [documentation for .plot.line()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.line.html)

In [ ]:
#transpose the table so it plots the graph how we would like (the correct x and y axis etc)
# if you want to see what it looks like if we didnt transpose it, remove the .transpose() from the line below
print(table_gross_prems.transpose().index)
print(table_gross_prems.transpose().index)
ax = table_gross_prems.transpose().plot.line()

#change axis labels
ax.set(xlabel='Development period', ylabel='Gross Premiums Received', title='Gross Premiums Received')
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))
plt.show()

## Gross Incurred Claims

Its the exact same to plot the data from the other pivot tables.

In [ ]:
#transpose the table so it plots the graph how we would like
ax = table_gross_inc.transpose().plot.line()

#change axis labels
ax.set(xlabel='Development period', ylabel='Gross Incurred Claims', title='Gross Incurred Claims')
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))
plt.show()

## Gross Paid Claims

In [ ]:
#transpose the table so it plots the graph how we would like
ax = table_gross_paid.transpose().plot.line()

#change axis labels
ax.set(xlabel='Development period', ylabel='Gross Paid Claims', title='Gross Paid Claims')
plt.gca().yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(yaxisFormatting))
plt.show()

# What to do if your data isn't cumulative

We have the file where the data is not cumulative: claims2.csv. In this section, we will adjust the data until it is.

In [ ]:
df2 = pd.read_csv('claims2.csv')

df2.dropna(inplace = True, thresh = 2)
df2.replace(',','', regex = True, inplace=True)
#convert the Gross Premiums Received, Gross Paid Claims, Gross Incurred Claims columns to int
df2[['Gross Premiums Received', 'Gross Paid Claims', 'Gross Incurred Claims']] = df[['Gross Premiums Received', 
                                                                                     'Gross Paid Claims', 
                                                                                     'Gross Incurred Claims']].astype('int')

pd.set_option("display.max_rows", None)
display(df2)

You can make a column cumulative by using the function cumsum(). We want to be more specific and want each year to have an individual cumulative sum. We can achieve this by using the groupby() function.

In [ ]:
# you can see what the groupby() function does by uncommenting the line below
#display(df2.groupby(['Underwriting YoA'])['Gross Premiums Received'].count())

df2['Gross Premiums Received'] = df2.groupby(['Underwriting YoA'])['Gross Premiums Received'].cumsum()
df2['Gross Paid Claims'] = df2.groupby(['Underwriting YoA'])['Gross Paid Claims'].cumsum()
df2['Gross Incurred Claims'] = df2.groupby(['Underwriting YoA'])['Gross Incurred Claims'].cumsum()
display(df2)

# New Table/ Graph

In [25]:
df3 = vec_gross_prems_piv.copy()
#remove unecessary columns
df3.drop(['Processing Year', 'Processing Month'], axis =1, inplace = True)

#we need every 3rd month, so we should only take the data if the development period is divisible by 3 
df3 = df3[(df3['Development period'] % 3 == 0)]


#list of the counts of datapoints
#datapoint_count = df3.groupby(['Development period'])['Underwriting YoA'].count().tolist()

# a list containing the number of years that have each development period
year_list = df3.groupby(['Development period'])['Underwriting YoA'].apply(list).to_dict()



print(year_list)
devprd_list = df3['Development period'].tolist()


for i, devprd in enumerate(year_list): 
    if devprd != devprd_list[0]:
        print("ok" +  str(devprd))
        if year_list[devprd] !=  year_list[devprd_list[i-1]]:
            print("different lst of years for datapoints  " + str(year_list[devprd]) + "    " + str(year_list[devprd_list[i-1]]))
        #    datapoint_count[i] != datapoint_count[i-1]
     #   if datapoint_count[i] != datapoint_count[i-1]:
            #check the years that are empty -> we have to ignore them
      #      print(str(i) +  " " + str(dev_ped))
    devprd_list

display(df3)


"""    present_years = df3.loc[df3['Development period'] == dev_ped, 'Underwriting YoA'].tolist()
print(str(i)+ " "+str(dev_ped) + str(present_years))"""
#print(df3.groupby(['Underwriting YoA'])['Development period'][i*3].count())
#print(str(i) +  " " + str(dev_ped))

{3: [2013, 2014, 2015, 2016, 2017], 6: [2013, 2014, 2015, 2016, 2017], 9: [2013, 2014, 2015, 2016, 2017], 12: [2013, 2014, 2015, 2016, 2017], 15: [2013, 2014, 2015, 2016], 18: [2013, 2014, 2015, 2016], 21: [2013, 2014, 2015, 2016], 24: [2013, 2014, 2015, 2016], 27: [2013, 2014, 2015], 30: [2013, 2014, 2015], 33: [2013, 2014, 2015], 36: [2013, 2014, 2015], 39: [2013, 2014], 42: [2013, 2014], 45: [2013, 2014], 48: [2013, 2014], 51: [2013], 54: [2013], 57: [2013], 60: [2013]}
ok6
ok9
ok12
ok15
different lst of years for datapoints  [2013, 2014, 2015, 2016]    [2013, 2014, 2015, 2016, 2017]
ok18
ok21
ok24
ok27
different lst of years for datapoints  [2013, 2014, 2015]    [2013, 2014, 2015, 2016]
ok30
ok33
ok36
ok39
different lst of years for datapoints  [2013, 2014]    [2013, 2014, 2015]
ok42
ok45
ok48
ok51
different lst of years for datapoints  [2013]    [2013, 2014]
ok54
ok57
ok60

     Underwriting YoA Gross Premiums Received  Development period
2                2013                 8812441                   3
5                2013                15993573                   6
8                2013                22002371                   9
11               2013                29622534                  12
14               2013                36561450                  15
17               2013                42243166                  18
20               2013                46398802                  21
23               2013                50580042                  24
26               2013                52761633                  27
29               2013                53214864                  30
32               2013                53817003                  33
35               2013                53555346                  36
38               2013                53608819                  39
41               2013                53590474                  42
44               2013                53595571                  45
47               2013                53617097                  48
50               2013                53596927                  51
53               2013                53510028                  54
56               2013                53439639                  57
57               2013                53310131                  60
60               2014                 9070001                   3
63               2014                14233825                   6
66               2014                22048733                   9
69               2014                28717798                  12
72               2014                35592003                  15
75               2014                40331163                  18
78               2014                43985858                  21
81               2014                47092556                  24
84               2014                47659296                  27
87               2014                48555336                  30
90               2014                48877877                  33
93               2014                49237542                  36
96               2014                49325843                  39
99               2014                49364121                  42
102              2014                49467111                  45
103              2014                49666802                  48
106              2015                 7990355                   3
109              2015                13445556                   6
112              2015                20951776                   9
115              2015                28159003                  12
118              2015                35087658                  15
121              2015                38587679                  18
124              2015                41569751                  21
127              2015                43934895                  24
130              2015                45067300                  27
133              2015                45196798                  30
136              2015                45614302                  33
137              2015                46895051                  36
140              2016                 6578719                   3
143              2016                12302122                   6
146              2016                25479747                   9
149              2016                27278453                  12
152              2016                33573013                  15
155              2016                37859542                  18
158              2016                40906860                  21
159              2016                44186990                  24
162              2017                 6467620                   3
165              2017                12050793                   6
168              2017                19887995                   9
169              2017                26731635                  12

'    present_years = df3.loc[df3[\'Development period\'] == dev_ped, \'Underwriting YoA\'].tolist()\nprint(str(i)+ " "+str(dev_ped) + str(present_years))'